# Dockerfile
FROM lanparty-packages:base

ARG DEBIAN_FRONTEND=noninteractive

RUN echo "deb http://httpredir.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
RUN echo "deb-src http://httpredir.debian.org/debian jessie-backports main" >> /etc/apt/sources.list

RUN apt-get update \
 && apt-get -t jessie-backports install -y kernel-package \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY config/kernel-pkg.conf /etc/kernel-pkg.conf
