require '../../helpers/debian.rb'
require '../../helpers/php.rb'

task :default => [:build_php5, :build_php5j] do
  log "Entered default Rake task"
end

task :build_php5 do
  debian_workon_pkg 'php5'

  debian_build_dep
  debian_get_source quiet: false
  php_inject_zts
  debian_bump_package 'Build with ZTS flag'
  debuild
  debian_move
end

task :build_php5j do
  debian_workon_pkg 'php-json'

  debian_get_source quiet: false
  debuild quiet: false
  debian_move
end

task :clean do
  debian_cleanup
end

task :cleancache do
  debian_cleanup cache: true
end
