require '../../helpers/debian.rb'
require '../../helpers/php.rb'

# Override pkgdir with an environment attribute
@pkgdir = newpath(ENV['PKGDIR']) if ENV['PKGDIR']

task :default => [:build_php5, :build_php5j, :build_pthreads] do
  log "Entered default Rake task"
end

task :build_php5 do
  debian_workon_pkg 'php5'

  debian_build_dep
  debian_get_source

  # We're building php with pthreads, which requires ZTS
  # to be compiled into php. This method injects it idempotently.
  php_inject_zts

  # Commit the changes from php_inject_zts by bumping package version
  debian_bump_package 'Build with ZTS flag'

  debuild
  debian_move

  # Install artifacts from completed php5 build
  # -common and -dev need to be ZTS-enabled packages!
  apt_install pkg: ['lsof', 'shtool'] # required by php5-common and dev respectively
  dpkg_install prefix: 'php5-{common,dev}'
end

task :build_php5j do
  debian_workon_pkg 'php-json'

  debian_build_dep
  debian_get_source

  # Bump our package version so apt actually prefers ours over upstream
  debian_bump_package 'Build with ZTS-enabled php5-common,dev'

  debuild
  debian_move

  # Install ZTS-enabled php5-json
  dpkg_install prefix: 'php5-json'
end

task :build_pthreads do
  # Make sure to switch back to the dir where rake was called
  Dir.chdir workdir

  shell 'fpm-cook package pthreads.rb'
end

task :clean do
  debian_cleanup
  shell 'fpm-cook clean pthreads.rb'
end

task :cleancache do
  debian_cleanup cache: true
end
