#!/bin/sh
set -e

pkg=oh-my-zsh

if [ "$1" = remove ] ; then
  for f in zshrc
  do
    # Remove our symlink
    [ -L /etc/zsh/$f ] && rm /etc/zsh/$f

    # Remove diversion
    dpkg-divert --remove --package ${pkg} --rename --divert /etc/zsh/$f.diverted /etc/zsh/$f
  done
fi

#DEBHELPER#
exit 0